name: Validate

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: validate-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - uses: "actions/checkout@v5"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
